pages:
  stage: deploy
  tags:
    - cbpf-runner
  script:
    - bun install --frozen-lockfile
    - bun run build
    - rm -rf public
    - mv dist public
  pages:
    publish: public
  artifacts:
    paths:
      - public
  only:
    - main
    